baseURL = 'https://slowlang.dev/'
languageCode = 'en-us'
title = 'The Slow Programming Language'
theme = 'hugo-book'

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1

[[menu.after]]
  name = "Playground"
  url = "/playground.html"
  weight = 5

[[menu.after]]
  name = "GitHub"
  url = "https://github.com/chrispyles/slow"
  weight = 10

[params]
  BookLogo = "/img/logo.png"
